l_english:
 SETTINGS_PAGE_GRAPHICS: "Grafica"
 SETTINGS_PAGE_GAME: "Gioco"
 SETTINGS_PAGE_SYSTEM: "Sistema"
 SETTINGS_PAGE_CONTROLS: "Controlli"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Interfaccia"
 SETTINGS_PAGE_AUDIO: "Audio"
 SETTINGS_CATEGORY_SCREEN: "Schermo"
 SETTINGS_CATEGORY_QUALITY: "Qualità"
 OPTION_EASY: "Facile"
 OPTION_NORMAL: "Normale"
 OPTION_HARD: "Difficile"
 OPTION_NEVER: "Mai"
 OPTION_MONTHLY: "Ogni mese"
 OPTION_HALFYEAR: "Ogni sei mesi"
 OPTION_YEARLY: "Ogni anno"
 OPTION_FIVE_YEAR: "Ogni cinque anni"
 OPTION_NO_AUTOSAVE: "Non salvare automaticamente"
 SETTINGS_CATEGORY_ACCOUNT: "Account"
 SETTINGS_CATEGORY_SYSTEM: "Sistema"
 SETTINGS_CATEGORY_CONTROLS: "Controlli"
 SETTINGS_CATEGORY_CAMERA: "Camera"
 SETTINGS_CATEGORY_AUDIO: "Audio"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Associazione Tasti"
 DISCARD: "Scarta"
 APPLY: "Applica"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Impostazioni"
 REQUIRES_RESTART: "Richiede il riavvio"
 REQUIRE_RESTART_DESCRIPTION: "Alcune impostazioni non avranno effetto finché non riavvierai il gioco."
 DISABLED_BECAUSE_IS_SET: "Disabilato perché '$SETTING_NAME$' è impostato su '$SETTING_VALUE$'"
 SETTINGS_INPUT_REMAP_INPUT: "Rimappa input"
 SETTINGS_INPUT_CONFIRM: "Conferma"
 SETTINGS_INPUT_CANCEL: "Indietro"
 SETTINGS_INPUT_CLEAR: "Ripristina"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Salva Profilo"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Carica Profilo"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Ripristina Predefinite"
 SETTINGS_INPUT_BINDING_TEXT: "Scegli un collegamento di input per l'azione '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Attenzione: questo assegnazione esiste già per '$INPUT_ACTION$'!\n\nPremendo '$SETTINGS_INPUT_CONFIRM$' cancellerà il vecchio vincolo"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Attenzione: l'assegnazione dei tasti non può essere composta solo da tasti modificatori."
 SETTINGS_PAGE_ACCOUNT: "Account"
 SETTING_TELEMETRY_CONSENT: "Invia dati telemetrici opzionali"
 SETTING_TELEMETRY_CONSENT_TOOLTIP:0 "#T Consenso alla Telemetria\n#!Consenti l'invio di dati telemetrici facoltativi a Paradox Interactive."